language: python

python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

services:
  - postgresql

install:
  - pip install -r requirements_test.txt

before_script:
  # stop the build if there are linting errors
  - flake8 .

script:
  - coverage run runtests.py

after_success:
  - codecov
