language: python

python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PYTHONPATH=$PYTHONPATH:$(pwd)
  - PGPORT=5433

install:
  - pip install -r requirements_test.txt

before_script:
  # Stop the build if there are linting errors.
  - flake8 .

  # Setting the password for user postgres so psycopg2 stop complaining.
  # With postgresql 10 the command is not the same as the one in the documentation,
  # see https://github.com/travis-ci/travis-ci/issues/8537
  - sudo -u postgres psql -U postgres -c "alter user postgres with password 'IN0vRycvrF';"

script:
  - pytest --cov=taskq tests/

after_success:
  - codecov
