# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exponential_backoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='retry_delay',
            field=models.DurationField(null=True, default=None),
        ),
    ]
