# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-08 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("taskq", "0002_add_retry_delay")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="retry_delay",
            field=models.DurationField(default=datetime.timedelta(0)),
        )
    ]
