# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-06 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskq', '0003_make_retry_delay_nonnullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
    ]
