# Generated by Django 3.2.20 on 2023-07-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("taskq", "0007_task_timeout")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Running"),
                    (2, "Success"),
                    (3, "Failed"),
                    (4, "Canceled"),
                    (5, "Fetched"),
                ],
                db_index=True,
                default=0,
            ),
        )
    ]
