# Generated by Django 3.2.20 on 2023-07-18 12:55

from django.db import migrations, models
import taskq.json


class Migration(migrations.Migration):

    dependencies = [
        ('taskq', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='function_args',
            field=models.JSONField(decoder=taskq.json.JSONDecoder, default=dict, encoder=taskq.json.JSONEncoder),
        ),
    ]
